---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-pipeline-app
  labels:
    app: first-pipeline-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-pipeline-app
  template:
    metadata:
      labels:
        app: first-pipeline-app
    spec:
      containers:
      - name: first-pipeline-app-container
        image: 225124233204.dkr.ecr.us-east-1.amazonaws.com/first-pipeline-script:latest
        ports:
        - containerPort: 3000
...
